stages:
  - deploy

pages:
  stage: deploy
  script:
    - echo "Deploiement de la présentation"
    - mv presentation public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "presentation"
  environment: production
